### ISSUE TITLE
GeneTest : Order of json array in test case incorrect

### ISSUE THREAD

**Issue by xiuchengquek** [oncoblocks/oncoblocks#2]
Hi,

Tried running `mvn test`. Test for `testGeneModel` in `org.oncoblocks.data_block.model.GeneTest` failed as order of alias in Gene Object is incorrect. Is the test made redundant since  `org.oncoblocks.data_block.mongo.GeneMongoTest` does the same thing and more? 

```
Failed tests:   testGeneModel(org.oncoblocks.data_block.model.GeneTest): expected:<...2","blah1...> but was:<...1","blah2...>
```

Quick fix is to change the order of `blah1` and `blah2` but I don't think that fixes the root of the problem. JSON array assumes order of element, but `aliases` implemented as a `HashSet` in Gene Object do not ? (although key get sorted some how by the google-gson library during the serialization step ? not sure )

Not too sure if this is required, but implementing `TreeSet` will ensure the `aliases` to be in natural order.

**Comment by TeweiLuo** [comment]
Hi Xiucheng,

I noticed this issue a while ago and brought it up in Base camp.

"The test cases (GeneTest); the assertion 

```
assertEquals({\"entrezGeneId\":675,\"standardGeneSymbol\":\"BRCA1\",\"aliases\":[\"blah1\",\"blah2\"]}", json);  
```

doesn't really work because the HashSet aliasSet won't be iterated in a defined order. Maybe we should fix this?"

To answer your question: yes, `HashSet` does not guarantee the iteration order of the set. I definitely need to think about this carefully when I start writing my own tests.

**Comment by xiuchengquek** [comment]
Oh didn't know that the issue have been raised prior. change `HashSet` to `TreeSet` seems like a quick fix. 

Cheers,
Quek

**Comment by ecerami** [comment]
Sorry if this caused confusion.  I just pushed out quick change to the unit test, such that it doesn't use aliases anymore.  This code was really just prototype code.
